apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: test-variables-aws
  title: Test Validation Variables AWS
  description: Ce template sert à vérifier que le questionnaire fonctionne.
spec:
  owner: platform-team
  type: service

  parameters:
    - title: Étape 1 - Nom
      required: [vm_name]
      properties:
        vm_name:
          title: Nom de la VM
          type: string

    - title: Étape 2 - Taille
      required: [aws_vm_instance_type_labelsize]
      properties:
        aws_vm_instance_type_labelsize:
          title: Taille choisie
          type: string
          enum: [small, medium, large, xlarge]

  steps:
    - id: log-check
      name: Affichage des valeurs saisies
      action: debug:log
      input:
        # On utilise uniquement 'message' pour l'action debug:log
        message: "Validation - Nom: ${{ parameters.vm_name }} | Taille: ${{ parameters.aws_vm_instance_type_labelsize }}"
