apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-aws-vm-final
  title: Provisionnement VM AWS via RHAAP
  description: Création d'une instance EC2 avec sélection de taille
spec:
  owner: platform-team
  type: service

  parameters:
    - title: Étape 1 - Identification et Accès
      required:
        - vm_name
        - AAP_TOKEN
      properties:
        vm_name:
          title: Nom de la VM
          type: string
        # Le token doit souvent être présent AVANT le picker pour éviter l'erreur 'includes'
        AAP_TOKEN:
          title: Token API Ansible
          type: string
          ui:field: password

    - title: Étape 2 - Configuration Technique
      required:
        - aws_vm_instance_type_labelsize
        - jobInventory
      properties:
        aws_vm_instance_type_labelsize:
          title: Taille de l'instance
          type: string
          enum: [small, medium, large, xlarge]
          default: small
        jobInventory:
          title: Inventaire
          type: string
          description: Sélectionnez l'inventaire cible
          ui:field: AAPResourcePicker
          ui:options:
            resource: inventories
            # Ajouter un filtre vide ou spécifique aide souvent à résoudre l'erreur 'includes'
            config:
              filter: {}

  steps:
    - id: launch-job
      name: Lancement du Job Ansible
      action: rhaap:launch-job-template
      input:
        token: ${{ parameters.AAP_TOKEN }}
        values:
          template: "AWS - EC2 Provisioning"
          inventory: ${{ parameters.jobInventory }}
          jobType: run
          extraVariables:
            aws_vm_name: ${{ parameters.vm_name }}
            aws_vm_instance_type_labelsize: ${{ parameters.aws_vm_instance_type_labelsize }}
