apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-aws-vm-rhaap
  title: Provisionnement VM AWS (RHAAP)
  description: Création d'une instance EC2 avec sélection de taille (Small à XLarge)
spec:
  owner: platform-team
  type: service

  parameters:
    - title: Étape 1 - Identification
      required:
        - vm_name
      properties:
        vm_name:
          title: Nom de la VM
          type: string
          description: Nom de l'instance sur AWS
        environment:
          title: Environnement
          type: string
          enum: [dev, staging, prod]
          default: dev

    - title: Étape 2 - Configuration AAP
      required:
        - aws_vm_instance_type_labelsize
        - jobInventory
      properties:
        aws_vm_instance_type_labelsize:
          title: Taille de l'instance
          type: string
          enum: [small, medium, large, xlarge]
          default: small
        jobInventory:
          title: Inventaire
          type: string
          description: Sélectionnez l'inventaire dans AAP
          ui:field: AAPResourcePicker
          ui:options:
            resource: inventories

  steps:
    - id: launch-job
      name: Lancement du Job Ansible
      action: rhaap:launch-job-template
      input:
        # Note: Vérifiez si votre token est dans parameters ou secrets
        token: ${{ parameters.AAP_TOKEN }} 
        values:
          # Remplacez par le nom exact de votre Job Template dans le Controller
          template: "AWS"
          inventory: ${{ parameters.jobInventory }}
          jobType: run
          extraVariables:
            aws_vm_name: ${{ parameters.vm_name }}
            aws_vm_instance_type_labelsize: ${{ parameters.aws_vm_instance_type_labelsize }}
            env_tag: ${{ parameters.environment }}

  output:
    links:
      - title: Suivre l'exécution du Job
        url: ${{ steps['launch-job'].output.data.url }}
