apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  # Changement : nom simplifié sans caractères spéciaux
  name: create-aws-vm-simple
  title: Provisionner une VM AWS
  description: Création de VM via AAP
spec:
  owner: ansible-authors
  type: service
  # Ajout du système comme dans votre exemple
  system: ansible

  parameters:
    - title: Étape 1 - Identification
      required:
        - vm_name
      properties:
        vm_name:
          title: Nom de la VM
          type: string
        environment:
          title: Environnement
          type: string
          enum: [dev, prod]

    - title: Étape 2 - Taille
      required:
        - aws_vm_instance_type_labelsize
      properties:
        aws_vm_instance_type_labelsize:
          title: Taille de l'instance
          type: string
          enum: [small, medium, large, xlarge]
          default: small

  steps:
    - id: trigger
      name: Lancement du Job
      # Attention : vérifiez que cette action est bien installée dans votre AAP
      action: ansible:controller:job:run
      input:
        jobTemplateName: "AWS - EC2 Provisioning"
        extraVars:
          aws_vm_name: ${{ parameters.vm_name }}
          aws_vm_instance_type_labelsize: ${{ parameters.aws_vm_instance_type_labelsize }}
